package section_20_funcional_calculo_lambda;

import org.junit.Test;

public class ProgramaFuncionaCalculoTest {

    @Test
    public void testMain() throws Exception {
        ProgramaFuncionaCalculo.main(new String[]{"args"});
    }

    @Test
    public void testNumerosPares() throws Exception {
        ProgramaFuncionaCalculo.numerosPares(new Integer[]{Integer.valueOf(0)});
    }
}

//Generated with love by TestMe :) Please report issues and submit feature requests at: http://weirddev.com/forum#!/testme